#!/usr/bin/env bash

pmount()
{
    if which udevil > /dev/null 2>&1; then
        udevil mount $1
        return 0
    fi

    if mount | grep -q $1; then
        echo "Device has been mounted"
        return
    fi

    local dev_name=`basename $1`

    if [ -e /tmp/$dev_name ]; then
        if [ ! -d /tmp/$dev_name ]; then
            echo "/tmp/$dev_name is existed but not a directory"
            return
        fi
    else
        mkdir /tmp/$dev_name
    fi

    sudo mount --option utf8,uid=$UID $1 /tmp/$dev_name
}

pumount()
{
    if which udevil > /dev/null 2>&1; then
        udevil umount $1
        return 0
    fi

    if ! mount | grep -q $1; then
        echo "Device hasn't been mounted"
        return
    fi

    echo "sync ..."
    sudo sync $1
    sudo umount $1
}

main()
{
    local cmd=$1
    local dev=$2

    if [ -z $dev ]; then
        echo "Error: No device specified" >&2
        exit 255
    fi

    if ! echo $dev | grep -q '$/dev/'; then
        echo 'Error: Only /dev/* device can be mounted' >&2
        exit 255
    fi

    case $cmd in
        *pmount)
            pmount $dev
            ;;
        *pumount)
            pumount $dev
            ;;
        *)
            echo "Unknow command $@" >&2
            exit 255
            ;;
    esac
}

main $0 $@
